repository_name: click
enabled: True
repoType: Github
url: https://github.com/pallets/click
url_pr: https://api.github.com/repos/pallets/click/pulls
pr_report:
  state: [open, closed, inprogress] 
  mail_to:
  mail_from:
  mail_subject:
  mail_body_template:
